# Generated by Django 3.1.2 on 2020-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDAutor', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('Nacionalidad', models.CharField(max_length=100)),
            ],
        ),
    ]
