# Generated by Django 3.1.2 on 2020-10-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDlibro', models.IntegerField()),
                ('Codigo', models.IntegerField()),
                ('Titulo', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=50)),
                ('Editorial', models.CharField(max_length=100)),
                ('NumPags', models.IntegerField()),
            ],
        ),
    ]
