# Generated by Django 3.1.2 on 2020-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDUsuario', models.IntegerField()),
                ('NumUsuario', models.IntegerField()),
                ('NIF', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
            ],
        ),
    ]
